# Generated by Django 2.2.13 on 2020-07-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200723_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'Задачи', 'verbose_name_plural': 'Задачи'},
        ),
    ]
